name: model-smartad-decision-tree
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train/decisiontree.py
          python train/logistic_regression.py
          python train/random_forest.py
          # python train/xgboost.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          # Logistic Regression
          echo "### Model Metrics" > report.md
          cat train/logistic_metrics.txt >> report.md

          echo "### Data Visualization" >> report.md
          cml-publish train/logistic_accuracy.png --md >> report.md

          # Decission Tree Classifier
          echo "### Model Metrics" > report.md
          cat train/decission_metrics.txt >> report.md

          echo "### Data Visualization" >> report.md
          cml-publish train/decision_tree_accuracy.png --md >> report.md


          # Random Forest Classifier
          echo "### Model Metrics" > report.md
          cat train/random_metrics.txt >> report.md

          echo "### Data Visualization" >> report.md
          cml-publish train/random_forest_accuracy.png --md >> report.md

          # # XGBoost Classifier
          # echo "### Model Metrics" > report.md
          # cat train/xgboost_metrics.txt >> report.md

          # echo "### Data Visualization" >> report.md
          # cml-publish train/xgboost_accuracy.png --md >> report.md


          cml-send-comment report.md
